import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

/**
 * BoardLink design tokens (from prototype builder).
 * Shared by the React app and static html/ prototypes (via html/boardlink.css).
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', './html/**/*.html'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9da',
        'on-primary': '#ffffff',
        background: '#fbf9fa',
        'on-error': '#ffffff',
        surface: '#fbf9fa',
        'surface-container-low': '#f6f3f4',
        'on-secondary-container': '#fefcff',
        'surface-container-highest': '#e4e2e3',
        'tertiary-container': '#002f1e',
        'surface-container-high': '#eae7e9',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container': '#f0edee',
        'primary-fixed': '#d9e3f6',
        'on-error-container': '#93000a',
        secondary: '#0058be',
        'outline-variant': '#c5c6cc',
        'tertiary-fixed': '#6ffbbe',
        'on-background': '#1b1b1d',
        error: '#ba1a1a',
        'surface-bright': '#fbf9fa',
        'surface-variant': '#e4e2e3',
        'primary-fixed-dim': '#bdc7d9',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#002113',
        outline: '#75777c',
        'on-primary-fixed-variant': '#3d4756',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#00a371',
        'on-surface': '#1b1b1d',
        'inverse-surface': '#303031',
        'error-container': '#ffdad6',
        'primary-container': '#1f2937',
        'secondary-fixed-dim': '#adc6ff',
        'secondary-container': '#2170e4',
        'surface-container-lowest': '#ffffff',
        primary: '#0a1422',
        'inverse-on-surface': '#f3f0f1',
        'on-primary-fixed': '#121c2a',
        'surface-tint': '#555f6f',
        'inverse-primary': '#bdc7d9',
        'secondary-fixed': '#d8e2ff',
        'on-primary-container': '#8690a1',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        tertiary: '#00180d',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#44474c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'max-width': '1280px',
        'gutter-desktop': '24px',
        lg: '24px',
        sm: '12px',
        xl: '32px',
        xs: '4px',
        base: '8px',
        'gutter-mobile': '16px',
        md: '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '22px',
          { lineHeight: '28px', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': [
          '20px',
          { lineHeight: '28px', fontWeight: '600' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [forms],
} satisfies Config
